import json
from functools import wraps
from app.models.url_model import URL

from app.models import url_model
from app.core.cache_utilities import get_cache, set_cache
from fastapi.encoders import jsonable_encoder
from sqlalchemy.ext.asyncio import AsyncSession


def cache_response(key_func, ttl=300):
    """Decorator to cache async function responses in Redis.

    Wraps an asynchronous function and caches its result using a Redis
    key generated by the provided key function. If a cached value exists,
    it is returned immediately, bypassing the function execution.

    Args:
        key_func: A callable that generates a unique cache key based on
            the function's arguments.
        ttl: Time-to-live in seconds for the cached value (default: 300).

    Returns:
        A decorated async function that returns cached results when available.

    Notes:
        - Cached responses are JSON-encoded before storage.
        - The original function result must be JSON-serializable.
    """
    def decorator(func):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            key = key_func(*args, **kwargs)

            cached = await get_cache(key)
            if cached:
                return json.loads(cached)
            
            result = await func(*args, **kwargs)

            encoded_result = jsonable_encoder(result)
            await set_cache(key, json.dumps(encoded_result), ttl)

            return result
        
        return wrapper
    return decorator
    

def url_cache_key(short_code: str, **kwargs):
    return f"url_shortcode:{short_code}"